#%RAML 1.0
title: Emanate Colaboration Contract
baseUri: https://casam2.ddns.net/
version: v1
description: |
  Make some description here...
protocols: [HTTP]
              
/propose:
    description: "Propose a collaboration contract to one or several users"
    post:
        description: "Propose a collaboration contract to one or several users"
        body:
            application/json:
                example: | 
                    {
                        "proposer": "collabuser1",              //  name of the account proposing the collaboration
                        "proposal_name": "contract1",           //  name of the contract
                        "price": 10000,                         //  price per second
                        "filename": "some_final_file_name",     //  the result filename of the collaboration
                        "requested": [                          //  needs at least one parner
                            {
                                "name": "colabuser2",           //  name of the collaboration partner account
                                "percentage": 10                //  percentage of the royalties for this partner
                                "filename": "filename_needed"   //  filename needed for this collaboration
                                "accepted": 0                   //  Should be ignored but must exist for now
                            }
                        ]
                    }                
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "success": true,
                                "data": { ... }
                            }
                            otherwise
                            {
                                "success": false,
                                "message": "the error message goes here"
                            }
              
/accept:
    description: "Accept a contract proposal"
    post:
        description: "Accept a contract proposal"
        body:
            application/json:
                example: | 
                    {
                        "from": "colabuser2", 
                        "proposer": "colabuser1", 
                        "name": "contract1"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "success": true,
                                "data": { ... }
                            }
                            otherwise
                            {
                                "success": false,
                                "message": "the error message goes here"
                            }

                            
                            
/reject:
    description: "Reject a contract proposal"
    post:
        description: "Reject a contract proposal"
        body:
            application/json:
                example: | 
                    {
                        "from": "colabuser2", 
                        "proposer": "colabuser1", 
                        "name": "contract1"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "success": true,
                                "data": { ... }
                            }
                            otherwise
                            {
                                "success": false,
                                "message": "the error message goes here"
                            }

                    
/execute:
    description: "Execute the contract"
    post:
        description: "Execute the contract"
        body:
            application/json:
                example: | 
                    {
                        "from": "colabuser2", 
                        "proposer": "colabuser1", 
                        "name": "user1"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "success": true,
                                "data": { ... }
                            }
                            otherwise
                            {
                                "success": false,
                                "message": "the error message goes here"
                            }

/addTrack:
    description: "Add a new track for a user"
    post:
        description: "Add a new track for a user"
        body:
            application/json:
                example: | 
                    {
                        "owner": "collabuser1",                     //  The owner of the track
                        "metadata":                                 //  All relevant data for the track
                        {
                            "trackName": "This is track 3",         //  The name of the track
                            "artistName": "Look, I'm an artist..."  //  The artist that made this track
                        }
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "success": true,
                                "data": { ... }
                            }
                            otherwise
                            {
                                "success": false,
                                "message": "the error message goes here"
                            }
                            
/getContract:
    description: "Get contract details"
    post:
        description: "Get contract details"
        body:
            application/json:
                example: | 
                    {
                        "proposer": "colabuser2", 
                        "contract": "contract1", 
                    }

/getTracks:
    description: "Get tracks for this user"
    post:
        description: "Get tracks for this user"
        body:
            application/json:
                example: | 
                    {
                        "owner": "colabuser2", //   The user that you want to get the tracks from
                    }
